version: '3'
services:
  app-keyboard-node:
    build: .
    container_name: app-keyboard-node
    image: oaklabs/app-keyboard-node:release-1.0.0-iohook
    network_mode: host
    privileged: true
    devices:
      - /dev/dri
      - /dev/bus/usb
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - /usr/share/fonts:/usr/share/fonts
      - /run/udev:/run/udev